services:
  db:
    ports:
      - 5432:5432
    image: postgres:latest
    environment:
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - TZ=Asia/Jakarta
    volumes:
      - ./docker-dev-volumes/pg_data:/var/lib/postgresql/data  # Persist PostgreSQL data
      - ./db/init:/docker-entrypoint-initdb.d  # Mounts init scripts
  fe:
    build:
      context: fe
      dockerfile: local.Dockerfile
    ports:
      - 2001:3000
    tty: true
    depends_on:
      - db
    volumes:
      - ./fe/app:/app
    environment:
       - PORT=3000
       - CHOKIDAR_USEPOLLING=true
       - NODE_ENV=development
       - WATCHPACK_POLLING=true 
       - a=c
   ## command: sh -c "yarn start"
  be:
    tty: true
    depends_on:
      - db
    volumes:
      - ./be/app:/var/www
      - ./be/app/public:/var/www/html
    command: bash -c "chown www-data:www-data -R /var/www/storage && php artisan migrate && apache2-foreground"
    build:
      context: be
      dockerfile: local.Dockerfile
    ports:
      - 2002:80